apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab77
  labels:
    app: frontend-lab77
spec:
  selector:
    matchLabels:
      app: frontend-lab77
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab77
    spec:
      containers:
        - name: frontend-lab77
          image: signalp77/frontend-lab77
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
