apiVersion: v1
kind: Service
metadata:
  name: frontend-lab77
  labels:
    name: frontend-lab77
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-lab77
  type: NodePort
